main: yy.gourlitburo.droo.Main
name: Droo
version: 0.0.1
api-version: 1.14
author: Zack Guard
description: Gyt sum werk dun, yeh?
commands:
  droo:
    description: Gyt sum werk dun, yeh?
    usage: /droo [<player>]
    permission: bukkit.op
    permission-message: Only ops (those with bukkit.op permission) are authorized to be enlightened by the inspirational words of Droo.
